language: csharp
solution: ESISharp.sln
dotnet: 2.0.0
mono: none
dist: trusty
sudo: required
script:
  - dotnet restore
  - dotnet build ./ESISharp/ -c Release
  - dotnet build ./ESISharp.AuthRouter/ -c Release
notifications:
  email:
    on_success: never
    on_failure: always