language: csharp
solution: ESISharp.sln
matrix:
  include:
    - dotnet: 2.0.0
      mono: none
      dist: trusty
      sudo: required
    - mono: latest
script:
  - dotnet restore
  - dotnet build ./ESISharp/ -c Release
  - dotnet build ./ESISharp.AuthRouter/ -c Release
after_success:
  - sonar-scanner
notifications:
  email:
    on_success: never
    on_failure: always
addons:
  sonarcloud:
    organization: wranders-github
    token:
      secure: $SONARCLOUD_TOKEN
    branches:
      - v1-core
